### ISSUE TITLE
Text nodes are replaced instead of mutated

### ISSUE THREAD

**Issue by dy** [WebReflection/domdiff#18]
If two text nodes have same content, they're still replaced, instead of mutated
```js
let el = document.createElement('a')
let foo = document.createTextNode('foo')
el.appendChild(foo)
let foo2 = document.createTextNode('foo') 
domdiff(el, [foo], [foo2])

el.firstChild !== foo // true
```
Not really expected behavior. Is that by design?

**Comment by dy** [comment]
Oh! It doesn't do patching even with real nodes.
I was completely mistaken about domdiff, I thought it does patching, like morphdom. Instead it replaces old nodes with new ones, even if they're the same.

**Comment by WebReflection** [comment]
Two different nodes are never the same, as these could have different listeners attached.

Domdiff never check the content, as it makes no sense.

Used via all libraries, domdiff never change anything by accident.

As mentioned before, you should likely stop using this library directly, as this is core for other libraries, not something to use in the wild manually.
