### ISSUE TITLE
Deep tree diffs?

### ISSUE THREAD

**Issue by shannonmoeller** [WebReflection/domdiff#2]
Does this library diff the whole tree or just the shallow list of children? All of the examples and tests are shallow.

**Comment by shannonmoeller** [comment]
Just found the answer at https://github.com/choojs/nanomorph/issues/85#issuecomment-350834055

> it's not suitable for nested nodes too, just lists of the same parent node.

**Comment by WebReflection** [comment]
Yeah, with `hyperHTML` which uses this engine you never need to care about nested nodes, these are always the nodes you expect them to be
